waithost: invalid options handling

diff --git a/waithost b/waithost
--- a/waithost
+++ b/waithost
@@ -10,11 +10,12 @@
 maxattempts=0
 delay=10
 
-while [ $# -gt 1 ]; do
+while [ $# -gt 0 ]; do
    case $1 in
       -m) shift; maxattempts=$1;;
       -d) shift; delay=$1;;
       --) shift; break;;
+      -*) echo "$(basename $0): invalid option '$1'" >&2; exit 1;;
       *)  break;;
    esac
    shift
@@ -26,7 +27,6 @@ if [ $# -ne 1 ]; then
 fi
 
 host=$1
-shift
 attempt=1
 
 while [ 1 ]; do
